// Auto-generated by scripts/build-world-data.mjs — do not edit by hand.

export type Continent =
  | "Africa"
  | "Antarctica"
  | "Asia"
  | "Europe"
  | "North America"
  | "Oceania"
  | "South America";

export interface Country {
  /** ISO 3166-1 alpha-2 */
  iso: string;
  name: string;
  continent: Continent;
  isUNMember: boolean;
  areaKm2: number;
  /** SVG path d-attribute in the projection's viewBox. Empty if not drawn at 1:50m. */
  d: string;
}

export interface WorldData {
  COUNTRIES: readonly Country[];
  MAP_VIEW_WIDTH: number;
  MAP_VIEW_HEIGHT: number;
}
